#!/usr/bin/env python3
"""
Train lightweight ML baselines for Alzheimer's EEG detection using the
precomputed feature pipeline.

Data inputs (already generated by the feature extraction notebook):
  - eeg_subject_features.npy : shape (n_subjects, 19, 4) float
  - eeg_subject_groups.npy   : shape (n_subjects,) labels: 'HC'/'AD'/'FTD'

This script performs SUBJECT-level evaluation (no epoch leakage) using
stratified k-fold CV and trains a final model on all available subjects.
"""

from __future__ import annotations

import argparse
import json
import sys
import warnings
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler

try:
    import joblib  # type: ignore
except Exception:  # pragma: no cover
    joblib = None


warnings.filterwarnings("ignore", category=RuntimeWarning, module=r"sklearn\.utils\.extmath")
warnings.filterwarnings(
    "ignore", category=RuntimeWarning, module=r"sklearn\.linear_model\._linear_loss"
)


def _finite_scale(X: np.ndarray) -> np.ndarray:
    """
    Guard against inf/NaN in features (can happen if a subject has near-zero power
    in a band, depending on how upstream features were computed/stored).
    """
    return np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)


def _log1p_clip(X: np.ndarray) -> np.ndarray:
    # Band powers are non-negative; log1p stabilizes wide dynamic range.
    return np.log1p(np.clip(X, a_min=0.0, a_max=None))


@dataclass(frozen=True)
class Metrics:
    accuracy: float
    roc_auc: float
    sensitivity: float
    specificity: float
    confusion_matrix: list[list[int]]  # [[tp, fn], [fp, tn]] with positive=AD


def _specificity(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0


def _sensitivity(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return float(tp / (tp + fn)) if (tp + fn) > 0 else 0.0


def load_npy(features_path: Path, groups_path: Path) -> tuple[np.ndarray, np.ndarray]:
    if not features_path.is_file():
        raise FileNotFoundError(f"Missing features file: {features_path}")
    if not groups_path.is_file():
        raise FileNotFoundError(f"Missing groups file: {groups_path}")

    X = np.load(features_path)
    y = np.load(groups_path, allow_pickle=True)

    if X.ndim != 3 or X.shape[1:] != (19, 4):
        raise ValueError(
            f"Expected features shape (n, 19, 4); got {X.shape} from {features_path}"
        )
    if y.ndim != 1 or y.shape[0] != X.shape[0]:
        raise ValueError(
            f"Expected groups shape (n,) aligned with features; got {y.shape} vs {X.shape}"
        )
    return X, y


def prepare_xy(
    X_19x4: np.ndarray, groups: np.ndarray, task: str
) -> tuple[np.ndarray, np.ndarray]:
    if task == "hc_vs_ad":
        keep = np.isin(groups, ["HC", "AD"])
        X = X_19x4[keep]
        y = (groups[keep] == "AD").astype(int)
    elif task == "all_3class":
        mapping = {"HC": 0, "AD": 1, "FTD": 2}
        keep = np.isin(groups, list(mapping.keys()))
        X = X_19x4[keep]
        y = np.array([mapping[g] for g in groups[keep]], dtype=int)
    else:
        raise ValueError(f"Unknown task: {task}")

    X_flat = _finite_scale(X.reshape(X.shape[0], -1).astype(np.float64))  # (n, 76)
    return X_flat, y


def make_model(name: str, seed: int) -> Pipeline:
    if name == "logreg":
        return Pipeline(
            steps=[
                (
                    "log1p",
                    FunctionTransformer(
                        _log1p_clip,
                        feature_names_out="one-to-one",
                    ),
                ),
                ("scale", StandardScaler()),
                (
                    "clf",
                    LogisticRegression(
                        max_iter=3000,
                        class_weight="balanced",
                        random_state=seed,
                        solver="liblinear",
                    ),
                ),
            ]
        )
    if name == "rf":
        return Pipeline(
            steps=[
                (
                    "clf",
                    RandomForestClassifier(
                        n_estimators=400,
                        max_depth=10,
                        class_weight="balanced",
                        random_state=seed,
                        n_jobs=1,
                    ),
                )
            ]
        )
    raise ValueError(f"Unknown model: {name}")


def evaluate_binary_cv(
    model: Pipeline, X: np.ndarray, y: np.ndarray, folds: int, seed: int, n_jobs: int
) -> Metrics:
    skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=seed)
    y_proba = cross_val_predict(
        model, X, y, cv=skf, method="predict_proba", n_jobs=n_jobs
    )[
        :, 1
    ]
    y_hat = (y_proba >= 0.5).astype(int)

    acc = float(accuracy_score(y, y_hat))
    auc = float(roc_auc_score(y, y_proba)) if len(np.unique(y)) == 2 else float("nan")
    sens = _sensitivity(y, y_hat)
    spec = _specificity(y, y_hat)
    tn, fp, fn, tp = confusion_matrix(y, y_hat).ravel()
    return Metrics(
        accuracy=acc,
        roc_auc=auc,
        sensitivity=sens,
        specificity=spec,
        confusion_matrix=[[int(tp), int(fn)], [int(fp), int(tn)]],
    )


def main() -> int:
    p = argparse.ArgumentParser(
        description="Train lightweight ML model(s) on precomputed EEG bandpower features."
    )
    p.add_argument(
        "--features",
        type=Path,
        default=Path("eeg_subject_features.npy"),
        help="Path to eeg_subject_features.npy (shape: n,19,4)",
    )
    p.add_argument(
        "--groups",
        type=Path,
        default=Path("eeg_subject_groups.npy"),
        help="Path to eeg_subject_groups.npy (labels: HC/AD/FTD)",
    )
    p.add_argument(
        "--task",
        choices=["hc_vs_ad", "all_3class"],
        default="hc_vs_ad",
        help="Classification task to train/evaluate",
    )
    p.add_argument(
        "--model",
        choices=["logreg", "rf"],
        default="logreg",
        help="Lightweight model family",
    )
    p.add_argument("--folds", type=int, default=5)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--n-jobs",
        type=int,
        default=1,
        help="Parallel jobs for cross-validation. Use 1 if multiprocessing is restricted.",
    )
    p.add_argument(
        "--outdir",
        type=Path,
        default=Path("artifacts"),
        help="Directory to save fitted model + metrics JSON",
    )
    args = p.parse_args()

    X_19x4, groups = load_npy(args.features, args.groups)
    X, y = prepare_xy(X_19x4, groups, task=args.task)
    if args.task != "hc_vs_ad":
        print(
            "Only hc_vs_ad is currently supported for ROC-AUC/sensitivity/specificity reporting.",
            file=sys.stderr,
        )
        return 2

    model = make_model(args.model, args.seed)
    metrics = evaluate_binary_cv(
        model, X, y, folds=args.folds, seed=args.seed, n_jobs=args.n_jobs
    )

    n_ad = int(y.sum())
    n_hc = int(len(y) - n_ad)
    print(f"Task: HC vs AD | Subjects: {len(y)} (AD={n_ad}, HC={n_hc})")
    print(f"Features: {X.shape[1]} (flattened 19 channels × 4 bands)")
    print(f"Model: {args.model} | CV: stratified {args.folds}-fold | seed={args.seed}")
    print(f"Accuracy: {metrics.accuracy:.4f}")
    print(f"ROC-AUC: {metrics.roc_auc:.4f}")
    print(f"Sensitivity (AD recall): {metrics.sensitivity:.4f}")
    print(f"Specificity (HC recall): {metrics.specificity:.4f}")
    tp, fn = metrics.confusion_matrix[0]
    fp, tn = metrics.confusion_matrix[1]
    print("Confusion (positive=AD):")
    print(f"  TP={tp}  FN={fn}")
    print(f"  FP={fp}  TN={tn}")

    args.outdir.mkdir(parents=True, exist_ok=True)
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    metrics_path = args.outdir / f"metrics_{args.task}_{args.model}_{run_id}.json"
    model_path = args.outdir / f"model_{args.task}_{args.model}_{run_id}.joblib"

    payload = {
        "run_id": run_id,
        "task": args.task,
        "model": args.model,
        "folds": args.folds,
        "seed": args.seed,
        "n_subjects": int(len(y)),
        "n_features": int(X.shape[1]),
        "metrics": asdict(metrics),
    }
    metrics_path.write_text(json.dumps(payload, indent=2) + "\n")

    if joblib is None:
        print(
            f"\nSaved metrics to {metrics_path}\n"
            "Could not import joblib, so the fitted model was not saved. "
            "Install joblib and rerun to export a .joblib artifact.",
            file=sys.stderr,
        )
        return 0

    model.fit(X, y)
    joblib.dump(model, model_path)
    print(f"\nSaved metrics: {metrics_path}")
    print(f"Saved fitted model: {model_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

